### ISSUE TITLE
Ignore circle.yml when no node version detected 

### ISSUE THREAD

**Issue by egoist** [egoist/travis-or-circle#1]
sometime we use multi version in circle.yml to test:

``` yml
test:
  override:
    - "nvm use 0.12 && npm test"
    - "nvm use 4 && npm test"
```

but in some other cases:

``` yml
test:
  override:
    - "npm run lint"
```

no version was mentioned, so error thrown:

``` bash
TypeError: Cannot read property '1' of null
    at /Users/e/dev/testen/node_modules/travis-or-circle/index.js:24:41
    at Array.map (native)
    at module.exports (/Users/e/dev/testen/node_modules/travis-or-circle/index.js:23:35)
    at main (/Users/e/dev/testen/testen:162:46)
    at next (native)
    at onFulfilled (/Users/e/dev/testen/node_modules/co/index.js:65:19)
    at /Users/e/dev/testen/node_modules/co/index.js:54:5
    at co (/Users/e/dev/testen/node_modules/co/index.js:50:10)
    at Object.<anonymous> (/Users/e/dev/testen/testen:155:1)
    at Module._compile (module.js:435:26)
```

Need fix.
