### ISSUE TITLE
new major version that returns {supported: Array<string>, unsupported: Array<string>}

### ISSUE THREAD

**Issue by balupton** [egoist/travis-or-circle#2]
Travis CI allows for testing many versions, while marking some of the versions as allowed failures:

``` yaml
node_js:
- '6'
- '8'
- '10'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '6'
```

It would be nice if this package returned the following in the above instance:

``` js
{
  supported: ['8', '10'],
  unsupported: ['6'],
  all: ['6', '8', '10']
}
```
